### ISSUE TITLE
Additional bracket when adding comment

### ISSUE THREAD

**Issue by nedy13** [redstar/m2-vscode#2]
Hi,

First of all...many thanks for the great extension.

I have a problem adding comments. If I open a parenthesis and then add an asterisk,

 the close tag is automatically set for the comment, but probably a bracket to bracket tag is also automatically set for a bracket. Is there a way to solve this?

![M2_comment-vscode](https://user-images.githubusercontent.com/4283170/87779047-7a0cd900-c82c-11ea-9382-bc5f0d1d6f2d.gif)

Best regards

**Comment by redstar** [comment]
Thanks for using my extension! I try to solve it. As I am working on a Modula-2 compiler, my plan is to evolve this extension over time, too.

**Comment by nedy13** [comment]
Thank you very much. I am very interested in more features :-)
Very cool would be "find references" and jump to function definition. Some workmates are using Sublime and it seems working for Modula-2.

**Comment by nedy13** [comment]
Seems that the issue is fixed with the latest VSCode version (1.52.1).
